### ISSUE TITLE
Allow for web UI logo/text to be overridden

### ISSUE THREAD

**Issue by astb01** [mailhog/MailHog-UI#61]
It would be nice if in the docker compose we could override the logo text and if possible provide our own logo, such as:

```yaml
environment:

   WEB-UI-SITE-NAME: 'foo'
   WEB-UI-LOGO: /mounted-path-to-img

```
